name: MkDocs Build
on:
  push:
    branches:
      - main  # Adjust this branch name as needed
permissions:
  contents: read
  packages: read
  repository: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material  # Adjust the theme if needed

      - name: Build MkDocs
        run: mkdocs build

      - name: Publish site
        run: |
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Updated Library"
          git push
