name: MkDocs Build
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add your workflow steps here

      - name: Publish site
        run: |
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Updated Library"
          git push
